openapi: 3.0.3
info:
  title: Urban Garden API
  version: 1.0.0
  description: API test description
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.redocly.com
paths: 
  /user:
    post:
      description: Creates user
      summary: User create
      operationId: '1'
      responses:
        '200':
          description: User data.
          content:
            application/json:
              schema:
                type: object
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                type: object

