openapi: 3.0.3
info:
  title: Urban Garden API
  version: 1.0.0
  description: API test description
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://random-d.uk/api/v2
paths: 
  /random:
    get:
      description: Get random duck
      summary: Get random duck
      operationId: '1'
      responses:
        '200':
          description: Get random duck.
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Duck not found.
          content:
            application/json:
              schema:
                type: object

