openapi: 3.0.3
info:
  title: Urban Garden API
  version: 1.0.0
  description: API test description
paths: {}
servers:
  - url: https://api.redocly.com
path: 
  /user:
    post:
      description: Creates user
      responses:
        '200':
          description: User data.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'